### ISSUE TITLE
Why include_context

### ISSUE THREAD

**Issue by Darhazer** [pboling/rspec-stubbed_env#10]
Why doing `include_context` every time for using the stub_env helper, instead of having
```ruby
RSpec::StubbedEnv::TestHelpers
```

in the spec_helper once?

**Comment by pboling** [comment]
Most of the time, I prefer to not pollute the global context as much as possible.  It makes it very clear which tests rely on ENV stubs.  OTOH, sometimes I like things to be more magical.  If you'd like to update the README in a PR with a section on that alternative mode, feel free!

**Comment by Darhazer** [comment]
What do you think to allow stubbing via meta-data, e.g. 
```ruby
include_context "with stubbed env", "FOO" => "bar"
```
in that case?

Happy to provide a PR. Also will provide PR to the documentation to point that the global include is still possible ;)

**Comment by pboling** [comment]
I love that.  That is the next logical step.  Please do send a PR if you have time!
