### ISSUE TITLE
Missing tag for 1.0.0 gem

### ISSUE THREAD

**Issue by Apteryks** [pboling/rspec-stubbed_env#7]
Hi!

I just noticed there is no corresponding git tag for the 1.0.0. release gem.  Would it be possible to add it?

Thanks!

**Comment by pboling** [comment]
Sure!  I'm also getting ready to update the gem, to allow RSpec `['>= 2.14', '< 4']`, so that it can be used while upgrading with `transpec`...  I'll have the tag up within a few hours.

**Comment by pboling** [comment]
@Apteryks tag is live. :)

**Comment by Apteryks** [comment]
Thank you!

**Comment by pboling** [comment]
v1.0.1 released and tagged with better stubbing (e.g. supporting access via `values_at`, which is required for AWS)
